"""Pure image transforms for message photos: resize/compress before storage,
and a heavily blurred preview for photos flagged "sensitive".

No database, no network — bytes in, bytes out — so this is unit-testable
directly, the same pattern as production.py / staff.py / costing.py.

The blur preview is generated by shrinking the photo to a tiny source
resolution *before* blurring, then scaling that back up. A blur filter alone
just smears full-resolution pixels and can be reversed with sharpening
tools; shrinking first actually discards the detail, so there is nothing
left to recover. That is what makes the preview safe to send to the
recipient before they choose to reveal the photo (point 12/13 of the
message-photo spec) — the client never has to download the full photo just
to show a blurred stand-in.
"""
import io
from typing import Tuple

from PIL import Image, ImageFilter

MAX_DISPLAY_DIM = 1600   # px, longest edge of the stored/shown photo
JPEG_QUALITY = 82
BLUR_SOURCE_DIM = 24     # px, longest edge the blur is generated from
BLUR_RADIUS = 12
BLUR_JPEG_QUALITY = 60   # a blurred preview compresses further with no visible loss


def _load_rgb(image_bytes: bytes) -> Image.Image:
    im = Image.open(io.BytesIO(image_bytes))
    im.load()  # fail fast here on corrupt/non-image bytes, not later on .save()
    return im.convert("RGB")


def _encode_jpeg(im: Image.Image, quality: int) -> bytes:
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=quality, optimize=True)
    return buf.getvalue()


def display_size(width: int, height: int) -> Tuple[int, int]:
    """The size a photo is shown/stored at — pure, so the blur preview can
    be resized to exactly match without re-deriving this logic."""
    if width <= MAX_DISPLAY_DIM and height <= MAX_DISPLAY_DIM:
        return width, height
    ratio = min(MAX_DISPLAY_DIM / width, MAX_DISPLAY_DIM / height)
    return max(1, round(width * ratio)), max(1, round(height * ratio))


def prepare_display(image_bytes: bytes) -> bytes:
    """Resize/compress the photo that is actually stored and shown — the
    raw upload from the device is never kept as-is."""
    im = _load_rgb(image_bytes)
    im.thumbnail(display_size(*im.size), Image.LANCZOS)
    return _encode_jpeg(im, JPEG_QUALITY)


def make_blur_preview(image_bytes: bytes) -> bytes:
    """A small, heavily blurred stand-in shown before the recipient reveals
    a "sensitive" photo, sized to match what prepare_display() would
    produce so the chat bubble doesn't resize on reveal."""
    im = _load_rgb(image_bytes)
    target_w, target_h = display_size(*im.size)
    small = im.copy()
    small.thumbnail((BLUR_SOURCE_DIM, BLUR_SOURCE_DIM), Image.LANCZOS)
    small = small.filter(ImageFilter.GaussianBlur(radius=BLUR_RADIUS))
    preview = small.resize((target_w, target_h), Image.LANCZOS)
    return _encode_jpeg(preview, BLUR_JPEG_QUALITY)
